# theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
# color_scheme: "dark"

# Site Settings
email: me@ronalddehaan.eu

# Enable/disable search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
    "Ronald's webpage @ UvA":
      - "//staff.science.uva.nl/r.dehaan/"
